/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadastroswing.telas;

import cadastroswing.entidades.Carro;
import cadastroswing.entidades.ListaCarros;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author vilson.moro
 */
public class Cadastrocarros extends javax.swing.JFrame {

    ListaCarros listacarros = new ListaCarros();
    //quando estiver acessando banco de dados preenche a lista 
    //com um método de consulta
    List<String> listaFord = new ArrayList<>();

    private void preencheListaFord() {
        listaFord.removeAll(listaFord);
        listaFord.add("Ford KA");
        listaFord.add("Fiesta");
        listaFord.add("Focus");
        listaFord.add("Eco sport");
    }

    List<String> listaChevrolet = new ArrayList<>();
    private void preencheListaChevrolet() {
        listaChevrolet.removeAll(listaChevrolet);
        listaChevrolet.add("Onix");
        listaChevrolet.add("Corsa");
    }

    List<String> listaWolks = new ArrayList<>();

    private void preencheListaWolks() {
        listaWolks.removeAll(listaWolks);
        listaWolks.add("Gol");
        listaWolks.add("Saveiro");
    }

    public Cadastrocarros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtPlaca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcMarca = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jcModelo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jtAnoFabricacao = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de carros");

        jLabel1.setText("Placa");

        jLabel2.setText("Marca");

        jcMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ford", "Chevrolet", "Wolkswaggen", "Toyota", "Honda", "Hyndai" }));
        jcMarca.setSelectedIndex(-1);
        jcMarca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcMarcaItemStateChanged(evt);
            }
        });

        jLabel3.setText("Modelo");

        jLabel4.setText("Ano fabricação");

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Listar todos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtAnoFabricacao, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jcMarca, javax.swing.GroupLayout.Alignment.LEADING, 0, 139, Short.MAX_VALUE)
                        .addComponent(jcModelo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtAnoFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Carro c = new Carro();
        c.setPlaca(jtPlaca.getText());
        c.setMarca(jcMarca.getItemAt(jcMarca.getSelectedIndex()));
        c.setModelo(jcModelo.getItemAt(jcModelo.getSelectedIndex()));
        c.setAnoFabricacao(Integer.parseInt(jtAnoFabricacao.getText()));
        listacarros.adiciona(c);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        listacarros.listarTodos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jcMarcaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcMarcaItemStateChanged
        jcModelo.removeAllItems();
        int selected = jcMarca.getSelectedIndex();
        switch (selected) {
            case 0: {
                jcModelo.removeAllItems();
                preencheListaFord();
                for (String item : listaFord) {
                    jcModelo.addItem(item);
                }
                break;
            }
            case 1: {
                jcModelo.removeAllItems();
                preencheListaChevrolet();
                for (String item : listaChevrolet) {
                    jcModelo.addItem(item);
                }
                break;
            }
            case 2:{
               jcModelo.removeAllItems();
               preencheListaWolks();
               for(String item: listaWolks){
                  jcModelo.addItem(item);
                } 
               break;
            }
            default:
                jcModelo.addItem("Não existe modelo");
        }
        /* if(jcMarca.getSelectedIndex() == 0){//ford
           preencheListaFord();
           for(String item: listaFord){
               jcModelo.addItem(item);
           }
       }
        else if(jcMarca.getSelectedIndex() ==  1){//chevrolet
            preencheListaChevrolet();
            for(String item: listaChevrolet){
               jcModelo.addItem(item);
           }
           }
        else{
            preencheListaWolks();
               for(String item: listaWolks){
                  jcModelo.addItem(item);
                }               
        }*/

    }//GEN-LAST:event_jcMarcaItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox<String> jcMarca;
    private javax.swing.JComboBox<String> jcModelo;
    private javax.swing.JTextField jtAnoFabricacao;
    private javax.swing.JTextField jtPlaca;
    // End of variables declaration//GEN-END:variables
}
